# Generated by Django 5.2.7 on 2025-10-07 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_livro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13, message='O ISBN deve ter exatamente 13 dígitos'), django.core.validators.RegexValidator('^\\d{13}$', 'O ISBN deve conter apenas números.')]),
        ),
    ]
